version: '3'
services:
  app:
    build: ./docker/drogon/
    ports:
      - "80:80"
    command:  /bin/bash -c "mkdir -p build && cd build && cmake .. && make && ./app"
    volumes:
      - ./app:/var/www
    working_dir:
      /var/www
    restart: always
    networks:
      - drogon
  db:
    image: postgres:14.5-alpine
    restart: always
    volumes:
      - ./db/data/:/var/lib/postgresql/data/:cached
      - ./db/initdb:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: user
      POSTGRES_DB: db
      POSTGRES_PASSWORD: password
    networks:
      - drogon
networks:
  drogon:
    driver: bridge

