/**
 *
 *  RestfulItemsCtrl.cc
 *  This file is generated by drogon_ctl
 *
 */

#include "RestfulItemsCtrl.h"
#include <string>


void RestfulItemsCtrl::getOne(const HttpRequestPtr &req,
                              std::function<void(const HttpResponsePtr &)> &&callback,
                              Items::PrimaryKeyType &&id)
{
    RestfulItemsCtrlBase::getOne(req, std::move(callback), std::move(id));
}


void RestfulItemsCtrl::updateOne(const HttpRequestPtr &req,
                                 std::function<void(const HttpResponsePtr &)> &&callback,
                                 Items::PrimaryKeyType &&id)
{
    RestfulItemsCtrlBase::updateOne(req, std::move(callback), std::move(id));
}


void RestfulItemsCtrl::deleteOne(const HttpRequestPtr &req,
                                 std::function<void(const HttpResponsePtr &)> &&callback,
                                 Items::PrimaryKeyType &&id)
{
    RestfulItemsCtrlBase::deleteOne(req, std::move(callback), std::move(id));
}

void RestfulItemsCtrl::get(const HttpRequestPtr &req,
                           std::function<void(const HttpResponsePtr &)> &&callback)
{
    RestfulItemsCtrlBase::get(req, std::move(callback));
}

void RestfulItemsCtrl::create(const HttpRequestPtr &req,
                              std::function<void(const HttpResponsePtr &)> &&callback)
{
    RestfulItemsCtrlBase::create(req, std::move(callback));
}
