/**
 *
 *  RestfulItemsCtrl.h
 *  This file is generated by drogon_ctl
 *
 */

#pragma once

#include <drogon/HttpController.h>
#include "RestfulItemsCtrlBase.h"

#include "Items.h"
using namespace drogon;
using namespace drogon_model::db;
/**
 * @brief this class is created by the drogon_ctl command.
 * this class is a restful API controller for reading and writing the items table.
 */

class RestfulItemsCtrl: public drogon::HttpController<RestfulItemsCtrl>, public RestfulItemsCtrlBase
{
  public:
    METHOD_LIST_BEGIN
    ADD_METHOD_TO(RestfulItemsCtrl::getOne,"/items/{1}",Get,Options);
    ADD_METHOD_TO(RestfulItemsCtrl::updateOne,"/items/{1}",Put,Options);
    ADD_METHOD_TO(RestfulItemsCtrl::deleteOne,"/items/{1}",Delete,Options);
    ADD_METHOD_TO(RestfulItemsCtrl::get,"/items",Get,Options);
    ADD_METHOD_TO(RestfulItemsCtrl::create,"/items",Post,Options);
    //ADD_METHOD_TO(RestfulItemsCtrl::update,"/items",Put,Options);
    METHOD_LIST_END
     
    void getOne(const HttpRequestPtr &req,
                std::function<void(const HttpResponsePtr &)> &&callback,
                Items::PrimaryKeyType &&id);
    void updateOne(const HttpRequestPtr &req,
                   std::function<void(const HttpResponsePtr &)> &&callback,
                   Items::PrimaryKeyType &&id);
    void deleteOne(const HttpRequestPtr &req,
                   std::function<void(const HttpResponsePtr &)> &&callback,
                   Items::PrimaryKeyType &&id);
    void get(const HttpRequestPtr &req,
             std::function<void(const HttpResponsePtr &)> &&callback);
    void create(const HttpRequestPtr &req,
             std::function<void(const HttpResponsePtr &)> &&callback);

};
